### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by marc-etienne**
Hi Cliff,

Thanks for this stuff to github. Here is a bunch of small improvements. Main motivation was to remove the flood of "RADIUS: {r}" in the system log, but I ended polishing a bit.

Cheers!

### CODE REVIEW

**Comment by igor10k** [comment]
Exactly what I was looking for. The debug flood was killing me.

**Comment by cliffrowley** [comment]
My word, I have no idea why I missed this..

**Comment by cliffrowley** [comment]
Merged, closed and @marc-etienne added as a contributor, if you want it - it's clear I can't be trusted to keep this updated ;-)

**Comment by igor10k** [comment]
@marc-etienne I'd like to note, that Allan, author of TextMate, said a few months ago that he'll accept a PR with this feature if someone manages to get it done. And it would be real nice to have blur support in TextMate out of the box. So if you're into contributing to TextMate, please do.

**Comment by igor10k** [comment]
@cliffrowley could you tag the latest commit as 1.1 version for example, so it shows up on Releases page in GitHub?

**Pull request merged**
